### ISSUE TITLE
License for this code

### ISSUE THREAD

**Issue by ghost** [williamthompsonj/HaXeRunner#1]
Hi William,

Thanks so much for this, I stumbled across this, but before I attempt to go through this code and use/modify some of it, I was wondering if there was any license you could please attach?

As I am going through it, I am hoping to send back some pull requests to update this to the latest version of haxeflixel too.

Thanks!

**Comment by williamthompsonj** [comment]
I'm sure you've moved on by now but I just found this request today. I've added a license file, it's open and free for use as public domain (CC0).
